
backend:
  name: git-gateway
  branch: main
media_folder: assets/uploads
public_folder: /assets/uploads
collections:
- name: pages
  label: Pages
  files:
  - file: index.md
    label: Home
    name: home
    fields:
    - {name: hero_title,label: Hero Title,widget: string}
    - {name: hero_subtitle,label: Hero Subtitle,widget: text}
    - {name: hero_image,label: Hero Image,widget: image,required: false}
    - {name: hero_video,label: Hero Video,widget: file,required: false}
    - {name: body,label: Body,widget: markdown}
- name: programs
  label: Programs
  folder: _programs
  create: true
  fields:
  - {name: title,label: Title,widget: string}
  - {name: age_range,label: Age Range,widget: string}
  - {name: body,label: Body,widget: markdown}
